# <span style="color:blue"> 이토록 쉬운 통계 & R </span>

<img src="../image/cover.png" width="200" height="400" align="left">  임경덕 지음

## PART 4 데이터 분석 도구, R

## 90% 순서대로 살펴보는 BR31-2 (31 일차)

   * 데이타프로젝트 (http://dataproject.xyz) 또는 (http://cafe.naver.com/dataartproject) 에 미리 저장된 스크립트를 다운 받을 수 있습니다.
   * 스크립트를 활용하면 직접 명령어를 입력하지 않고 저장된 명령어들을 실행할 수 있습니다.
   * 지금 설치된 R 버젼은 3.4.3 입니다. 제목 BR31 은 Basic R 31 로 3.1 버젼입니다. 그러나 큰 차이는 없을 것 같습니다.
   * page 253 substr 함수부터


In [2]:
# substr() 스트링의 부분을 가져올 경우 , 1 부터 시작하여 10, 11, 12, 13 번째 문자를 가져와서 열을 만듬.
substr("ABCDEFGHIJKLMNOPQRSTUVWXYZ", 10, 13)

[1] "JKLM"

In [3]:
substr("가A나B다C", 3, 4)

[1] "나B"

In [5]:
# = 또는 <- 으로 갑을 저장 하기
x = 1
x
y <- 2
y

[1] 1

[1] 2

In [6]:
x = c("A","D")
x

[1] "A" "D"

In [7]:
y = rep(x,2)
y

[1] "A" "D" "A" "D"

In [8]:
# 부등호 (> 또는 <) 와 등호 (== , !=)
3 > 0

[1] TRUE

In [9]:
3 < 0

[1] FALSE

In [12]:
# 3 은 0 과 같다. 결과는 false
3 == 0

[1] FALSE

In [13]:
# 3은 0 이 아니다
3 != 0

[1] TRUE

In [14]:
# 1 에서 5 까지 벡터를 만들고,  1 에서 3 까지는 false 4, 5 는 TRUE
1:5 > 3

[1] FALSE FALSE FALSE  TRUE  TRUE

In [15]:
# %in% 로 논리 연산하기
# 1 에서 10 까지 숫자열에서 3, 7, 9 가 있는지 판단
v1 = 1:10
v1 %in% c(3,7,9)

[1] FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE

In [16]:
v2 = c("서울", "인천", "부산", "경기", "강원", "대전", "대구", "제주", "광주", "울산")
v2 %in% c("부산","대구")

[1] FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE

In [20]:
# &(AND) |(OR) 연산자
# v1 은 1 에서 10 까지 숫자 이고 V2 은 서울 인천 등 10개 도시를 나열한것입니다.
# v1 에서 3, 7, 9 번째만  true 인것 과 부산 대구, 즉 3, 7 번째만 true 인것의 and 이므로 7 번째만 true 로 표시된다.
v1
v2
(v1 %in% c(3,7,9)) & (v2 %in% c("부산", "대구"))

[1]  1  2  3  4  5  6  7  8  9 10

[1] "서울" "인천" "부산" "경기" "강원" "대전" "대구" "제주" "광주" "울산"

[1] FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE

In [21]:
# 이번에는 3,7,9 true 와 3,7 true or 이므로 3,7,9 가 true 로 나옵니다.
(v1 %in% c(3,7,9)) | (v2 %in% c("부산", "대구"))

[1] FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE

In [23]:
# cbind 와 rbind 로 열/행 결합하기
# cbind 는 column bind 행 bind,  rbind 는 열 바인드
rbind(c("A", "B", "C"), c("X", "Y", "Z"))

[,1] [,2] [,3]
[1,] A    B    C   
[2,] X    Y    Z

In [24]:
cbind(c("A", "B", "C"), c("X", "Y", "Z"))

[,1] [,2]
[1,] A    X   
[2,] B    Y   
[3,] C    Z

In [45]:
# [] 로 부분 선택하기 , 인덱스 활용
# 20개의 홀수 수열을 만들기
x = 1:20*2 -1
x

[1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39

In [30]:
# 이중에서 1, 13, 19 만 값을 가져온다
x[c(1,13,19)]

[1]  1 25 37

In [36]:
xy = rbind(1:3, 7:9, 13:15)
xy

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  7    8    9  
[3,] 13   14   15

In [38]:
# 2번째 행 의 모든 열을  가져오기
xy[2,]

[1] 7 8 9

In [40]:
# 모든 행에서, 열은 1, 3번만 가져오기
xy[,c(1,3)]

[,1] [,2]
[1,]  1    3  
[2,]  7    9  
[3,] 13   15

In [42]:
# 2번째 열을 빼고 나머지만 가져오기
xy[,-2]

[,1] [,2]
[1,]  1    3  
[2,]  7    9  
[3,] 13   15

In [44]:
# 2행 3번째 열 만 가져오기
xy[2,3]

[1] 9