# <span style="color:blue"> 이토록 쉬운 통계 & R </span>

<img src="../image/cover.png" width="200" height="400" align="left">  임경덕 지음

## PART 4 데이터 분석 도구, R

## 95% R로 분석 다시보기-2-treat-4-선형대수기초 대응분석관련-2 (42일차)

   * 데이타프로젝트 (http://dataproject.xyz) 또는 (http://cafe.naver.com/dataartproject) 에 미리 저장된 스크립트를 다운 받을 수 있습니다.
   * 스크립트를 활용하면 직접 명령어를 입력하지 않고 저장된 명령어들을 실행할 수 있습니다.

### 데이터 파일은 dataartproject.xyz 에 있습니다.

# 두개의 범주형 변수의 관계 찾기 -- treat - 대응분석 정리

## 진료과목 중 내과만 자세히 살피기  -- 대응분석

## 대응분석 관련 정리 계속

대응분석을 설명하기 위해서는 몇가지 기본적인 내용의 정리가 필요합니다. 따라서 관련 내용을 먼저 정리 하고 진료 과목에 대한 대응 분석을 설명할 예정입니다.
여기서 대응분석이라는 것은 일반적으로 두개의 범주형 변수의 관계에 대한 독립성 여부는 카이제곱 분석에 의하여 P 검정을 살펴보게 됩니다.

그러나 다수준인 경우에는 분석시에 복잡한 양상을 띄게 됩니다. 따라서 이 경우에는 수준별 대응 분석을 하게 됩니다. 대응분석은 범주형 변수의 각 수준을 계량화하여 2차원 그래프 상에서 표현하여 두 범주형 변수가 변화는 관계를 살펴보는 것입니다.

이런 내용을 이해 하기 위해서는 선형 대수와 관련 해서 몇가지 기초적인 지식이 필요합니다.

####  예제들과 관련한 정리 (http://darkpgmr.tistory.com/105)
지금까지는 내용을 예제로서만 설명을 하여 따라갔지만, 그 이유에 대해서 간략하게 설명하고, 다음 SVD 관련 정리합니다.

1. 선형대수학에서 다루는 고유값, 고유벡터 을 소개하는 이유

##### 벡터의 소개 

* 먼저 하나의 벡터는 임의의 두개 이상의 벡터로 나누어 질 수 있습니다. 즉 $\mathbf V= \mathbf V_1 + \mathbf V_2$
* 선형독립 또는 일차독립(linearly independent) 란 벡터들이 집합이 있을떼 임의의 벡터들의 합으로 나타냈을 없을 경우에 선형독립 또는 일차독립이라고 합니다. (말이 좀 어려운데..)
   * 예를 가지고 설명하면 선형독립의 가장 일반적인 예가 3차원 공간에서 $\mathbf x, \mathbf y, \mathbf z$ 를 생각할 수 있습니다.
   * $\mathbf x, \mathbf y, \mathbf z$ 는 각각 길이가 1인 단위 벡터 입니다.
   * 3차원 좌표(공간)에서 원점(0,0,0) 부터 임의 점까지 벡터 $\mathbf v$ 는 $\mathbf x, \mathbf y, \mathbf z$ 로 표시 할 수 있습니다. 이것을 $\mathbf v = \mathbf x + \mathbf y + \mathbf z$ 로 표시합니다.
   * 3차원 공간 어느 점도 이런 방식으로 표시 할 수 있으며, 이때 $\mathbf x, \mathbf y, \mathbf z$ 을 기저 벡터라고 하고 이들은 서로 선형독립이라고 합니다. 왜냐하면 $\mathbf x, \mathbf y, \mathbf z$ 어느것 하나 다른 것의 합으로 표시 할 수 없기 때문입니다.
   * 벡터의 집합 $\mathbf V = \{\mathbf v_1,\mathbf v_2,\cdots,\mathbf v_n \}$ 이 선형독립 또는 일차독립이라 함은 $\mathbf V$ 에 있는 어떤 요소들을 다른 요소들의 합으로 표시 할 수 없습니다.
   
   
##### 벡터에 행렬을 곱할때
* 행렬에 벡터를 곱하는 기하학적 의미는 벡터의 길이를 변화 시키거나 벡터의 방향을 변화 시킨다. [참조](https://wikidocs.net/4050)
* 행렬에 벡터를 곱한다는 형식은 행렬 $\mathbf A$ 에 벡터 $\mathbf V$ 가 있을 때 $\mathbf A \cdot \mathbf V$ 와 같은 모습니다.


##### 고유값과 고유벡터
* 행렬에서 고유값을 구하는 이유는 다음과 같습니다.
* 고유값, 고유벡터를 구하는 식은 다음과 같습니다. $\mathbf E  \mathbf V = \lambda \mathbf V$ 
* 행렬 $\mathbf E$ 를 벡터 $\mathbf V$ 에 곱하였을때 벡터의 변화가 자기 자신의 상수배 되는 0이 아닌 벡터가 있으며 상수배를 고유값, 변하지 않는 벡터를 고유벡터라고 합니다.

##### 고유값, 고유벡터 의 전개 : 대각화
* 고유값 식의 전개는 다음과 같이 할 수 있습니다. 여기서 $\mathbf P \mathbf P^{-1} = \mathbf P^{-1} \mathbf P = \mathbf I$
* $\mathbf I = \begin{pmatrix} 1 & 0 & \cdots & 0 \\ 0 & 1 & \ddots & \vdots \\ \vdots & \ddots & \ddots & 0 \\ 0 & 0 & \cdots & 1 \\ \end{pmatrix} $
* $\mathbf E \mathbf V = \lambda \mathbf V \Rightarrow \mathbf E \mathbf P \mathbf P^{-1} \mathbf V= \lambda \mathbf P \mathbf P^{-1} \mathbf V = \mathbf P (\lambda \mathbf P^{-1} \mathbf V) \Rightarrow \mathbf P^{-1}\mathbf E \mathbf P (\mathbf P^{-1} \mathbf V) = \lambda (\mathbf P^{-1} \mathbf V)$
* Let $\mathbf X = \mathbf P^{-1} \mathbf V$ 라고 놓으면 $\mathbf P^{-1} \mathbf E \mathbf P \mathbf X = \lambda \mathbf X$


* 또는 
* $\mathbf E \mathbf V = \lambda \mathbf V \Rightarrow \mathbf E \mathbf P^{-1} \mathbf P \mathbf V= \lambda \mathbf P^{-1} \mathbf P \mathbf V = \mathbf P^{-1} (\lambda \mathbf P \mathbf V) \Rightarrow \mathbf P\mathbf E \mathbf P^{-1} (\mathbf P \mathbf V) = \lambda (\mathbf P \mathbf V)$
* Let $\mathbf X = \mathbf P \mathbf V$ 라고 놓으면 $\mathbf P \mathbf E \mathbf P^{-1} \mathbf X = \lambda \mathbf X$

* 이것을 해석해 보면, 어떤 행렬 $\mathbf P$ 가 있어서 그 $\mathbf P$ 가 $\mathbf E$ 에 적용하여 $\mathbf P^{-1} \mathbf E \mathbf P$ 또는 $\mathbf P \mathbf E \mathbf P^{-1}$ 을 대각화 할 수 있는 그런 $\mathbf P$ 가 있어
* 대각화 가  $\mathbf \Lambda = \begin{pmatrix} \lambda_1 & 0 & \cdots & 0 \\ 0 & \lambda_2 & \ddots & \vdots \\ \vdots & \ddots & \ddots & 0 \\ 0 & 0 & \cdots & \lambda_n \\ \end{pmatrix} $ , 여기서 $\lambda_i$ 는 각 고유값 이다, 

$\mathbf \Lambda \mathbf X = \lambda \mathbf X$ 가 되는 $\mathbf X$ 를 구할 수 있습니다. 이때 $\mathbf X = \mathbf P \mathbf V$ 가 됩니다.  따라서 어떤 행렬 $\mathbf E$ 가 주어지면, 그 행렬에 관계되는 고유값및 고유벡터를  구할 수 있으며, 또한 $\mathbf P$ 를 구할 수 있어 고유벡터를 회전시켜 대각화 행렬의 기저 벡터들이 됩니다.

그런 행렬 $\mathbf P$ 의 형태는 다음과 같습니다.

##### 대각화 시키는 행렬 분해

*  $\mathbf E  \mathbf V = \lambda \mathbf V$  에서 살펴보면

* 우변은 예를 들면 $3 \times 3$ 행렬의 경우를 보면 $\lambda$ 는 $\lambda_1, \lambda_2, \lambda_3$ 최대 서로 다는 3개가 나올 수 있으며 고유벡터 역시 3개가 나온다.
* $\mathbf P$ 를 고유값들을 열벡터로 하면 다음과 같이 됩니다.
* $ \mathbf P = \begin{pmatrix} \mathrm v_{11} & \mathrm v_{12} & \mathrm v_{13} \\ \mathrm v_{21} & \mathrm v_{22} & \mathrm v_{23} \\ \mathrm v_{31} & \mathrm v_{32} & \mathrm v_{33} \\ \end{pmatrix} $
* 그럼 $ \mathbf P \mathbf \Lambda = \begin{pmatrix} \mathrm v_{11} & \mathrm v_{12} & \mathrm v_{13} \\ \mathrm v_{21} & \mathrm v_{22} & \mathrm v_{23} \\ \mathrm v_{31} & \mathrm v_{32} & \mathrm v_{33} \\ \end{pmatrix}\begin{pmatrix} \lambda_1 & 0 & 0 \\ 0 & \lambda_2 & 0 \\ 0 & 0 & \lambda_3 \\ \end{pmatrix} = \begin{pmatrix} \lambda_1 \mathrm v_{11} & \lambda_2\mathrm v_{12} & \lambda_3\mathrm v_{13} \\ \lambda_1\mathrm v_{21} & \lambda_2\mathrm v_{22} & \lambda_3\mathrm v_{23} \\ \lambda_1\mathrm v_{31} & \lambda_2\mathrm v_{32} & \lambda_3\mathrm v_{33} \\ \end{pmatrix} $ 이 된다.

* 행렬 $\mathbf E$ 의 고유값, 고유벡터들을 각각 $\lambda_i, \mathrm v_i, i = 1,2,\cdots, n$ 이라고 하면
$$
\begin{align}
\mathbf E \mathrm v_1 &= \lambda_1 \mathrm v_1 \\
\mathbf E \mathrm v_2 &= \lambda_2 \mathrm v_2 \\
\mathbf E \mathrm v_3 &= \lambda_3 \mathrm v_3 \\
\vdots \\
\mathbf E \mathrm v_n &= \lambda_n \mathrm v_n
\end{align}
$$

* 이제 이것을 한번에 표현하면 다음과 같이 됩니다.
$$
\begin{align}
\mathbf E [\mathrm v_1, \mathrm v_2, \cdots, \mathrm v_n] &= [\lambda_1 \mathrm v_1, \lambda_2 \mathrm v_2, \cdots, \lambda_n \mathrm v_n ] \\
&= [\mathrm v_1, \mathrm v_2, \cdots, \mathrm v_n] \begin{pmatrix} \lambda_1 & 0 & 0 \\ 0 & \ddots & 0 \\ 0 & 0 & \lambda_n \\ \end{pmatrix}
\end{align}
\Rightarrow \mathbf E \mathbf P = \mathbf P \mathbf \Lambda \Rightarrow \mathbf E = \mathbf P \mathbf \Lambda \mathbf P^{-1} \Rightarrow \mathbf P^{-1} \mathbf E \mathbf P
$$

## 왜 이런것은 하는지????????

* 범주형 자료들을 모은 통계 관측치 또는 일반 관측된 자료들은 행렬로 표현을 할 수 있습니다. 즉 행렬은 우리가 보고 관측된 기록입니다.
* 예를 들면 월별 판매기록, 년도별 인구증가율, 품목변 판매량 등등은 2차원 행렬로 표현이 가능합니다. 
* 이런 관측된 자료들을 분석을 할 경우에 고유값을 구하고 고유벡터를 구하게 되면 2차원 행렬 요소들이 부분적인 군집을 이루게 되고, 그 군집을 이루는 기저 벡터들이 원인이나 기타 설명할 수 있는 변수로 표시 할 수 있게 됩니다.
* 이런 이유로 고유값과 고유벡터는 매우 중요한 것이라고 할 수 있습니다.

### 이제 정방형 행렬($n \times n)$ 에서 일반화 ($m \times n$) 행렬로 진행합니다. 먼저 R 에서 행렬 처리 명령어를 살펴봅니다.

#### R 에서 행렬 생성

* 1. rbind (row bind), 2 cbind (column bind), 3 matrix

In [4]:
# rbind
row_1 = c(1,2,3,4)
row_2 = c(5,6,7,8)

data_rbind = rbind(row_1, row_2)
print(data_rbind)


      [,1] [,2] [,3] [,4]
row_1    1    2    3    4
row_2    5    6    7    8


In [6]:
#col naming
colnames(data_rbind) = paste("col_", 1:4, sep="")
print(data_rbind)

      col_1 col_2 col_3 col_4
row_1     1     2     3     4
row_2     5     6     7     8


In [9]:
# cbind
col_1 <- c(1, 5)
col_2 <- c(2, 6)
col_3 <- c(3, 7)
col_4 <- c(4, 8)

data_cbind = cbind(col_1, col_2, col_3, col_4)
print(data_cbind)

     col_1 col_2 col_3 col_4
[1,]     1     2     3     4
[2,]     5     6     7     8


In [10]:
# row naming
rownames(data_cbind) = paste("row_", 1:2, sep="")
print(data_cbind)

      col_1 col_2 col_3 col_4
row_1     1     2     3     4
row_2     5     6     7     8


In [12]:
# matrix
raw_data = c(1, 2, 3, 4, 5, 6, 7, 8)
data_matrix = matrix(raw_data, nrow=2, byrow=TRUE)
print(data_matrix)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8


In [13]:
dim(data_matrix)

[1] 2 4

In [14]:
dimnames(data_matrix) = list("row" = c("row_1", "row_2"), "column" = c("col_1", "col_2", "col_3", "col_4"))
print(data_matrix)

       column
row     col_1 col_2 col_3 col_4
  row_1     1     2     3     4
  row_2     5     6     7     8


* 행렬에서 행이나 열을 하나만 인덱싱하게 되면 벡터로 바뀌는데, 행렬로 계속 차원을 유지 하고 싶을 경우 drop = FALSE 사용합니다.

In [20]:
print(data_matrix)
data_index = data_matrix[,2]
''
print(data_index)

       column
row     col_1 col_2 col_3 col_4
  row_1     1     2     3     4
  row_2     5     6     7     8


[1] ""

row_1 row_2 
    2     6 


In [24]:
class(data_matrix)
class(data_index)
str(data_matrix)
str(data_index)

[1] "matrix"

[1] "numeric"

 num [1:2, 1:4] 1 5 2 6 3 7 4 8
 - attr(*, "dimnames")=List of 2
  ..$ row   : chr [1:2] "row_1" "row_2"
  ..$ column: chr [1:4] "col_1" "col_2" "col_3" "col_4"
 Named num [1:2] 2 6
 - attr(*, "names")= chr [1:2] "row_1" "row_2"


In [25]:
# using drop = false
data_drop_false = data_matrix[, 2, drop = FALSE]
print(data_drop_false)

       column
row     col_2
  row_1     2
  row_2     6


In [26]:
class(data_drop_false)

[1] "matrix"

In [27]:
str(data_drop_false)

 num [1:2, 1] 2 6
 - attr(*, "dimnames")=List of 2
  ..$ row   : chr [1:2] "row_1" "row_2"
  ..$ column: chr "col_2"


#### 특수 행렬들
* null matrix : 영행렬
* 정방행렬 : regular matrix
* 전치행렬(transpose matrix)
* 대칭행렬(symmetry matrix)
* 상삼각행렬(upper triangular matrix)
* 하삼각행렬(lower triangular matrix)
* 대각행렬(diagonal matrix)
* 항등행렬(identity matrix)


##### 영행렬
* 모든 원소가 0 인 행렬

In [41]:
# 영행렬
A_zero = matrix(rep(0,9), nrow = 3, byrow = TRUE)
print(A_zero)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0


##### 정방행렬(Square matrix)
* 행렬의 차수(dim) 이 $n \times n$ 인 행렬

In [39]:
# 정방행렬  차수가 n X n 인 행렬
A_r = matrix(c(3, 1, -2, 4, 0, 6, 4, 2, 5, -3, 0, 10, -4, 5, 12, 6), 4)
print(A_r)
diag(A_r)
dim(A_r)

     [,1] [,2] [,3] [,4]
[1,]    3    0    5   -4
[2,]    1    6   -3    5
[3,]   -2    4    0   12
[4,]    4    2   10    6


[1] 3 6 0 6

[1] 4 4

##### 전치행렬
* $A_{ij} \rightarrow A_{ji}$
* $A^t$ 로 표시

In [33]:
# 전치행렬
A = matrix(c(1:9), nrow=3, byrow=TRUE)
print(A)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [34]:
# t 함수 : 전치행렬
A_t = t(A)
print(A_t)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [35]:
B = matrix(c(4:9), nc = 3)
print(B)

     [,1] [,2] [,3]
[1,]    4    6    8
[2,]    5    7    9


In [36]:
B_t = t(B)
print(B_t)

     [,1] [,2]
[1,]    4    5
[2,]    6    7
[3,]    8    9


##### 대칭행렬
* $A_{ij} = A_{ji}$ 인 행렬
* $A = A^t$ 이면 A 는 대칭행렬입니다.

In [40]:
# 대칭행렬
A_s = matrix(c(3.5, 0.6, 2.1, 0.6, 4.5, 1.9, 2.1, 1.9, 6.8), 3)
print(A_s)

     [,1] [,2] [,3]
[1,]  3.5  0.6  2.1
[2,]  0.6  4.5  1.9
[3,]  2.1  1.9  6.8


##### 상삼각행렬
* 대각원소 아래 모든 원소는 0 즉 $i \gt j$ 인 모든 $i,j$ 에 대해서 $A_{ij} = 0$

In [43]:
A_u = matrix(c(1, 0, 0, 0, 2, 0, 0, 0, 3, -1, 3, 0, 4, 2, 0, 5), 4)
print(A_u)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    0    0   -1    2
[3,]    0    0    3    0
[4,]    0    0    0    5


In [44]:
Matrix::isTriangular(A_u)

[1] TRUE
attr(,"kind")
[1] "U"

##### 대각행렬
* 정방행렬에서 모든 비대각원소가 0 일때, 즉 $i \ne j$ 인 모든 $i,j$ 에 대해서 $A_{ij} = 0$

In [45]:
A_d = diag(c(3,5,-4,7))
print(A_d)

     [,1] [,2] [,3] [,4]
[1,]    3    0    0    0
[2,]    0    5    0    0
[3,]    0    0   -4    0
[4,]    0    0    0    7


##### 항등행렬 (identity matrix)
* 모든 대각원소의 값이 1 인 항렬
* $ \mathbf I$ 로 표시하고, $\mathbf A \mathbf I$ = $\mathbf I \mathbf A = \mathbf A$

In [46]:
A_i = diag(3)
print(A_i)

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


In [47]:
print(3 * A_i)

     [,1] [,2] [,3]
[1,]    3    0    0
[2,]    0    3    0
[3,]    0    0    3


#### R 에서 행렬의 연산
* +, -, *, /, ^, %*%, cbind(), rbind(), colMeans(), rowMeans(), colSums(), rowSums(), t()

##### 행렬 내 각 숫자끼리의 연산 : +, -, *, /, ^

In [48]:
# 행렬 X 와 행렬 Y 생성
X = matrix(1:4, nrow = 2, ncol= 2, byrow = FALSE, dimnames = NULL)
print(X)

     [,1] [,2]
[1,]    1    3
[2,]    2    4


In [49]:
Y = matrix(5:8, nrow = 2, ncol = 2, byrow = TRUE, dimnames = NULL)
print(Y)

     [,1] [,2]
[1,]    5    6
[2,]    7    8


In [59]:
# 행렬 X, Y 사칙연산들
X
Y
'더하기 X + Y'
print(X + Y)

'빼기 X - Y'
print(X - Y)

'곱하기 X * Y  ; 행렬곱하고는 다릅니다. 행렬곱은 %*% 입니다.'
print(X * Y)

'나누기 X /Y'
print(zapsmall(X /Y))

'지수곱 X^Y'
print(X^Y)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 5    6   
[2,] 7    8

[1] "더하기 X + Y"

     [,1] [,2]
[1,]    6    9
[2,]    9   12


[1] "빼기 X - Y"

     [,1] [,2]
[1,]   -4   -3
[2,]   -5   -4


[1] "곱하기 X * Y  ; 행렬곱하고는 다릅니다. 행렬곱은 %*% 입니다."

     [,1] [,2]
[1,]    5   18
[2,]   14   32


[1] "나누기 X /Y"

          [,1] [,2]
[1,] 0.2000000  0.5
[2,] 0.2857143  0.5


[1] "지수곱 X^Y"

     [,1]  [,2]
[1,]    1   729
[2,]  128 65536


#### 행렬 곱 : X%*%Y

In [60]:
'X'
print(X)
'Y'
print(Y)
'X%*%Y'
print(X%*%Y)

[1] "X"

     [,1] [,2]
[1,]    1    3
[2,]    2    4


[1] "Y"

     [,1] [,2]
[1,]    5    6
[2,]    7    8


[1] "X%*%Y"

     [,1] [,2]
[1,]   26   30
[2,]   38   44


#### 행렬 세로결합 cbind(), 가로결합 rbind()

In [61]:
# 세로결합 cbind()
'X'
print(X)
'Y'
print(Y)
'세로결합 cbind(X,Y)'
print(cbind(X,Y))
'가로결합 rbind(X,Y)'
print(rbind(X,Y))

[1] "X"

     [,1] [,2]
[1,]    1    3
[2,]    2    4


[1] "Y"

     [,1] [,2]
[1,]    5    6
[2,]    7    8


[1] "세로결합 cbind(X,Y)"

     [,1] [,2] [,3] [,4]
[1,]    1    3    5    6
[2,]    2    4    7    8


[1] "가로결합 rbind(X,Y)"

     [,1] [,2]
[1,]    1    3
[2,]    2    4
[3,]    5    6
[4,]    7    8


#### 열 평균 colMeans(), 행평균 rowMeans()

In [64]:
'X'
print(X)
'colMeans(X)'
print(colMeans(X))
'rowMeans(X)'
print(rowMeans(X))

[1] "X"

     [,1] [,2]
[1,]    1    3
[2,]    2    4


[1] "colMeans(X)"

[1] 1.5 3.5


[1] "rowMeans(X)"

[1] 2 3


#### 열합계 colSums(), 행합계 rowSums()

In [69]:
'X'
print(X)

'colSums(X)'
print(colSums(X))

'rowSums(X)'
print(rowSums(X))

'colSums(X, na.rm = TRUE) na.rm = TRUE: 값이 없으면 계산 no'
print(colSums(X, na.rm = TRUE))

'rowSums(X, na.rm = TRUE)'
print(rowSums(X, na.rm = TRUE))

[1] "X"

     [,1] [,2]
[1,]    1    3
[2,]    2    4


[1] "colSums(X)"

[1] 3 7


[1] "rowSums(X)"

[1] 4 6


[1] "colSums(X, na.rm = TRUE) na.rm = TRUE: 값이 없으면 계산 no"

[1] 3 7


[1] "rowSums(X, na.rm = TRUE)"

[1] 4 6


In [75]:
'na.omit(), na.rm = TRUE 확인'
library(MASS)
str(Cars93)

'값이 없는 row 확인'
print(sum(is.na(Cars93)))

'값이 없는 row 제거: na.omit(Cars93)'
Cars93_na.omit = na.omit(Cars93)
sum(is.na(Cars93_na.omit))


[1] "na.omit(), na.rm = TRUE 확인"

'data.frame':	93 obs. of  27 variables:
 $ Manufacturer      : Factor w/ 32 levels "Acura","Audi",..: 1 1 2 2 3 4 4 4 4 5 ...
 $ Model             : Factor w/ 93 levels "100","190E","240",..: 49 56 9 1 6 24 54 74 73 35 ...
 $ Type              : Factor w/ 6 levels "Compact","Large",..: 4 3 1 3 3 3 2 2 3 2 ...
 $ Min.Price         : num  12.9 29.2 25.9 30.8 23.7 14.2 19.9 22.6 26.3 33 ...
 $ Price             : num  15.9 33.9 29.1 37.7 30 15.7 20.8 23.7 26.3 34.7 ...
 $ Max.Price         : num  18.8 38.7 32.3 44.6 36.2 17.3 21.7 24.9 26.3 36.3 ...
 $ MPG.city          : int  25 18 20 19 22 22 19 16 19 16 ...
 $ MPG.highway       : int  31 25 26 26 30 31 28 25 27 25 ...
 $ AirBags           : Factor w/ 3 levels "Driver & Passenger",..: 3 1 2 1 2 2 2 2 2 2 ...
 $ DriveTrain        : Factor w/ 3 levels "4WD","Front",..: 2 2 2 2 3 2 2 3 2 2 ...
 $ Cylinders         : Factor w/ 6 levels "3","4","5","6",..: 2 4 4 4 2 2 4 4 4 5 ...
 $ EngineSize        : num  1.8 3.2 2.8 2.8 3.5 2.2 3.8 5.7 3.

[1] "값이 없는 row 확인"

[1] 13


[1] "값이 없는 row 제거: na.omit(Cars93)"

[1] 0

#### 직교행렬 (Orthogonal matrix)
##### 정직교 행렬
* x 의 norm : $||x|| = \sqrt{(x^tx)}$
* 정규벡터: norm 이 1 인 벡터 $u = \dfrac{x}{||x||}$

In [84]:
x_1 = c(2,3,4,1)
print(x_1)
' F or f is Frobian norm : 유클리드 norm: 대표적: 피타고라스 정리'
print(norm(matrix(x_1, 4), "F"))
'sum(x_1^2)'
print(sum(x_1^2))
'sqrt(sum(x_1^2))'
print(sqrt(sum(x_1^2)))

[1] 2 3 4 1


[1] " F or f is Frobian norm : 유클리드 norm: 대표적: 피타고라스 정리"

[1] 5.477226


[1] "sum(x_1^2)"

[1] 30


[1] "sqrt(sum(x_1^2))"

[1] 5.477226


* 같은 차수의 벡터 $x, y$ 에서 $x^t y = 0$ 일때 $x, y$ 는 서로 직교

In [85]:
x_2 = c(1,2,2,4)
print(x_2)
y_2 = c(6,3,-2,-2)
print(y_2)

[1] 1 2 2 4
[1]  6  3 -2 -2


In [87]:
'x_2 %*% y_2'
print(x_2%*%y_2)
'x_2 와 y_2 는 서로 직교입니다.'

[1] "x_2 %*% y_2"

     [,1]
[1,]    0


[1] "x_2 와 y_2 는 서로 직교입니다."

* 두 정규벡터가 직교할 때 그 두 벡터를 정직교벡터라고 함 $\mathbf u^t\mathbf u = 1, \mathbf v^t \mathbf v = 1, \mathbf u \mathbf v = 0$

In [92]:
u_1 = c(1,1,3,3,4)
u_1_n = sqrt(sum(u_1^2))
'u_1'
print(u_1)
'u_1 norm'
print(u_1_n)
u_1_u = 1/u_1_n * u_1
'u_1_u'
print(u_1_u)
v_1 = c(-0.1,-0.9, -0.1, -0.1, 0.4)
v_1_n = sqrt(sum(v_1^2))
v_1_u = 1/v_1_n * v_1
'v_1_u'
print(v_1_u)

[1] "u_1"

[1] 1 1 3 3 4


[1] "u_1 norm"

[1] 6


[1] "u_1_u"

[1] 0.1666667 0.1666667 0.5000000 0.5000000 0.6666667


[1] "v_1_u"

[1] -0.1 -0.9 -0.1 -0.1  0.4


In [96]:
'u_1_u %*% u_1_u'
print(u_1_u %*% u_1_u)
'v_1_u %*% v_1_u'
print(v_1_u %*% v_1_u)
'u_1_u %*% v_1_u'
print(u_1_u %*% v_1_u)

[1] "u_1_u %*% u_1_u"

     [,1]
[1,]    1


[1] "v_1_u %*% v_1_u"

     [,1]
[1,]    1


[1] "u_1_u %*% v_1_u"

     [,1]
[1,]    0


* 정 직교 집합: 집합에 있는 모든 벡터들이 정규 벡터이고 서로 다른 벡터 끼리 직교
   * 행렬 $\mathbf P_{r \times c}$ 의 행들이 정 직교 집합을 이룰 때, 정 직교 행을 가진다고 함. 그러면 $\mathbf P \mathbf P^t = \mathbf I_{r}$ 이 성립합니다. 역이 항상 성립하지는 않습니다.

In [97]:
P17 = matrix(c(1, 0, 0, 1, 0, 0), 2)
print(P17)

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0


In [100]:
'P17 %*% t(P17)'
print(P17 %*% t(P17))

[1] "P17 %*% t(P17)"

     [,1] [,2]
[1,]    1    0
[2,]    0    1


In [101]:
't(P17) %*% P17'
print(t(P17) %*% P17)

[1] "t(P17) %*% P17"

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    0


In [102]:
P18 = 1/sqrt(6)*matrix(c(sqrt(2), sqrt(3), 1, sqrt(2), -sqrt(3), 1, sqrt(2), 0, -2), 3)
print(P18)

          [,1]       [,2]       [,3]
[1,] 0.5773503  0.5773503  0.5773503
[2,] 0.7071068 -0.7071068  0.0000000
[3,] 0.4082483  0.4082483 -0.8164966


In [104]:
print(round(t(P18) %*% P18, digits=5))

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


In [106]:
print(P18 %*% t(P18))

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


다음에는 커널, 차원정리, 계수, 고유값 n 차원, 마크코프, 그리고 대망의 SVD 과정, 그리고 대응분석을 진행 할 예정입니다.